MACHINE Devoir1Partie2
SETS
    Livre = {li1,li2,li3}
;   Membre = {me1,me2,me3}

CONSTANTS pret, reservation, Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8

PROPERTIES
    pret : ... /* Question 1 */
&   pret = ...  /* Question 2 */
&   reservation : ... /* Question 3 */
&   reservation =  ... /* Question 4 */
&   Q1 = ... /* Question 5 */
&   Q2 = ... /* Question 6 */
&   Q3 = ... /* Question 7 */
&   Q4 = ... /* Question 8 */
&   Q5 = ... /* Question 9 */
&   ... /* Question 10 */
&   Q7 = ... /* Question 11 */
&   Q8 = ... /* Question 12 */
&   ... /* Question 13 */
END

